#!/bin/bash

file='./data/char_professions.txt'
rm -fr $file
timestamp=$(date +%s%N)
while read -a row
do
             case ${row[0]} in
		'0')
                        class='Fighter'
                        ;;
                '1')
                        class='Warrior'
                        ;;
                '2')
                        class='Gladiator'
                        ;;
                '3')
                        class='Warlord'
                        ;;
                '4')
                        class='Knight'
                        ;;
                '5')
                        class='Paladin'
                        ;;
                '6')
                        class='DarkAvenger'
                        ;;
                '7')
                        class='Rogue'
                        ;;
                '8')
                        class='TreasureHunter'
                        ;;
                '9')
                        class='Hawkeye'
                        ;;
                '10')
                        class='Mage'
                        ;;
                '11')
                        class='Wizard'
                        ;;
                '12')
                        class='Sorceror'
                        ;;
                '13')
                        class='Necromancer'
                        ;;
                '14')
                        class='Warlock'
                        ;;
                '15')
                        class='Cleric'
                        ;;
                '16')
                        class='Bishop'
                        ;;
                '17')
                        class='Prophet'
                        ;;
                '18')
                        class='ElvenFighter'
                        ;;
                '19')
                        class='ElvenKnight'
                        ;;
                '20')
                        class='TempleKnight'
                        ;;
                '21')
                        class='SwordSinger'
                        ;;
                '22')
                        class='ElvenScout'
                        ;;
                '23')
                        class='PlainsWalker'
                        ;;
                '24')
                        class='SilverRanger'
                        ;;
                '25')
                        class='ElvenMage'
                        ;;
                '26')
                        class='ElvenWizard'
                        ;;
                '27')
                        class='Spellsinger'
                        ;;
                '28')
                        class='ElementalSummoner'
                        ;;
                '29')
                        class='Oracle'
                        ;;
                '30')
                        class='Elder'
                        ;;
                '31')
                        class='DarkFighter'
                        ;;
                '32')
                        class='PalusKnight'
                        ;;
                '33')
                        class='ShillienKnight'
                        ;;
                '34')
                        class='Bladedancer'
                        ;;
                '35')
                        class='Assassin'
                        ;;
                '36')
                        class='AbyssWalker'
                        ;;
                '37')
                        class='PhantomRanger'
                        ;;
                '38')
                        class='DarkMage'
                        ;;
                '39')
                        class='DarkWizard'
                        ;;
                '40')
                        class='Spellhowler'
                        ;;
                '41')
                        class='PhantomSummoner'
                        ;;
                '42')
                        class='ShillienOracle'
                        ;;
                '43')
                        class='ShillenElder'
                        ;;
                '44')
                        class='OrcFighter'
                        ;;
                '45')
                        class='OrcRaider'
                        ;;
                '46')
                        class='Destroyer'
                        ;;
                '47')
                        class='OrcMonk'
                        ;;
                '48')
                        class='Tyrant'
                        ;;
                '49')
                        class='OrcMage'
                        ;;
                '50')
                        class='OrcShaman'
                        ;;
                '51')
                        class='Overlord'
                        ;;
                '52')
                        class='Warcryer'
                        ;;
                '53')
                        class='DwarvenFighter'
                        ;;
                '54')
                        class='Scavenger'
                        ;;
                '55')
                        class='BountyHunter'
                        ;;
                '56')
                        class='Artisan'
                        ;;
                '57')
                        class='Warsmith'
                        ;;
                '88')
                        class='Duelist'
                        ;;
                '89')
                        class='Dreadnought'
                        ;;
                '90')
                        class='PhoenixKnight'
                        ;;
                '91')
                        class='HellKnight'
                        ;;
                '92')
                        class='Sagittarius'
                        ;;
                '93')
                        class='Adventurer'
                        ;;
                '94')
                        class='Archmage'
                        ;;
                '95')
                        class='Soultaker'
                        ;;
                '96')
                        class='ArcanaLord'
                        ;;
                '97')
                        class='Cardinal'
                        ;;
                '98')
                        class='Hierophant'
                        ;;
                '99')
                        class='EvaTemplar'
                        ;;
                '100')
                        class='SwordMuse'
                        ;;
                '101')
                        class='WindRider'
                        ;;
                '102')
                        class='MoonlightSentinel'
                        ;;
                '103')
                        class='MysticMuse'
                        ;;
                '104')
                        class='ElementalMaster'
                        ;;
                '105')
                        class='EvaSaint'
                        ;;
                '106')
                        class='ShillienTemplar'
                        ;;
                '107')
                        class='SpectralDancer'
                        ;;
                '108')
                        class='GhostHunter'
                        ;;
                '109')
                        class='GhostSentinel'
                        ;;
                '110')
                        class='StormScreamer'
                        ;;
                '111')
                        class='SpectralMaster'
                        ;;
                '112')
                        class='ShillienSaint'
                        ;;
                '113')
                        class='Titan'
                        ;;
                '114')
                        class='GrandKhavatari'
                        ;;
                '115')
                        class='Dominator'
                        ;;
                '116')
                        class='Doomcryer'
                        ;;
                '117')
                        class='FortuneSeeker'
                        ;;
                '118')
                        class='Maestro'
                        ;;
                '123')
                        class='MaleSoldier'
                        ;;
                '124')
                        class='FemaleSoldier'
                        ;;
                '125')
                        class='Trooper'
                        ;;
                '126')
                        class='Warder'
                        ;;
                '127')
                        class='Berserker'
                        ;;
                '128')
                        class='MaleSoulbreaker'
                        ;;
                '129')
                        class='FemaleSoulbreaker'
                        ;;
                '130')
                        class='Arbalester'
                        ;;
                '131')
                        class='Doombringer'
                        ;;
                '132')
                        class='MaleSoulhound'
                        ;;
                '133')
                        class='FemaleSoulhound'
                        ;;
                '134')
                        class='Trickster'
                        ;;
                '135')
                        class='Inspector'
                        ;;
                '136')
                        class='Judicator'
                        ;;
                 *)
                        class='Unknown'
                        ;;
        esac
    echo "char_proffesion,char_classid=$class,char_name=${row[1]} value=${row[2]} $timestamp" >> $file
done < <(echo "select classid,char_name,level from characters" | mysql l2jgs -u root)

sed -i '1d' $file
curl -i -XPOST 'http://localhost:8086/write?db=l2j' --data-binary @$file
